services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-api
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - messaging
    volumes:
      - .:/usr/src/app
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  messaging:
    image: rabbitmq:3-management
    container_name: messaging
    ports:
      - "5672:5672"     # Porta AMQP
      - "15672:15672"   # Interface web de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_USER}
    volumes:
      - messaging_data:/var/lib/rabbitmq

volumes:
  db_data:
  messaging_data:
